// Generated by scripts/sync_protocol.py. Edit protocol/models.json.
export const Model = {
  "GPT_6_LUNA": "gpt-6-luna",
  "GPT_5_4_MINI": "gpt-5.4-mini",
  "CLAUDE_HAIKU_4_5": "claude-haiku-4-5",
  "MISTRAL_SMALL_4": "mistral-small-2603",
  "GPT_OSS_120B": "tinfoil/gpt-oss-120b",
  "GEMMA_4_31B": "tinfoil/gemma4-31b",
  "GPT_5_6_TERRA": "gpt-5.6-terra",
  "CLAUDE_SONNET_4_6": "claude-sonnet-4-6",
  "GPT_5_6_SOL": "gpt-5.6-sol",
  "CLAUDE_OPUS_4_8": "claude-opus-4-8"
} as const;
