"""Copy the shared model snapshot into independently distributable SDK packages."""

import argparse
import ast
import json
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]


def generated_files():
    models = json.loads((ROOT / "protocol/models.json").read_text())
    constants = {m["constant"]: m["id"] for m in models}
    python = ROOT / "sdks/python/duckai/catalog.py"
    source = python.read_text()
    tree = ast.parse(source)
    enum = next(n for n in tree.body if isinstance(n, ast.ClassDef) and n.name == "Model")
    lines = source.splitlines(keepends=True)
    replacement = "class Model(StrEnum):\n" + "".join(
        f"    {name} = {json.dumps(value)}\n" for name, value in constants.items()
    )
    source = "".join(lines[: enum.lineno - 1]) + replacement + "".join(lines[enum.end_lineno :])
    data = json.dumps(models, indent=2) + "\n"
    ts = "// Generated by scripts/sync_protocol.py. Edit protocol/models.json.\n"
    ts += "export const Model = " + json.dumps(constants, indent=2) + " as const;\n"
    outputs = {
        python: source,
        ROOT / "sdks/python/duckai/_catalog_data.json": data,
        ROOT / "sdks/typescript/src/catalog-data.json": data,
        ROOT / "sdks/typescript/src/model-constants.ts": ts,
        ROOT / "sdks/python/docs/file-formats.md": (ROOT / "docs/file-formats.md").read_text(),
    }
    return outputs


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args()
    mismatches = []
    for path, content in generated_files().items():
        if args.check:
            if not path.exists() or path.read_text() != content:
                mismatches.append(str(path.relative_to(ROOT)))
        else:
            path.write_text(content)
    if mismatches:
        raise SystemExit(
            "Run python scripts/sync_protocol.py; stale files: " + ", ".join(mismatches)
        )


if __name__ == "__main__":
    main()
